// Compares the JS optimiser against fixtures generated by the Python implementation.
// Fixtures hold the real per-day price/load arrays plus Python's profit for each day, so
// a mismatch localises to the exact day rather than just a changed annual total.
import { readFileSync } from 'node:fs';
import { makeCfg, solveDay } from '../js/optimiser.js';

const fixtures = JSON.parse(readFileSync(new URL('./fixtures.json', import.meta.url)));
let failed = 0;

for (const fx of fixtures) {
  const cfg = makeCfg(fx.params);
  let worstDay = null, worstDiff = 0, totalJs = 0, totalPy = 0, badDays = 0;
  for (const d of fx.days) {
    const r = solveDay(d.imp, d.exp, d.load, cfg, fx.mode, fx.allowExport);
    totalJs += r.profit;
    totalPy += d.profit;
    const diff = Math.abs(r.profit - d.profit);
    if (diff > 1e-6) badDays++;
    if (diff > worstDiff) { worstDiff = diff; worstDay = d.day; }
  }
  const totalDiff = Math.abs(totalJs - totalPy);
  const ok = worstDiff < 1e-6 && totalDiff < 1e-4;
  if (!ok) failed++;
  console.log(
    `${ok ? 'PASS' : 'FAIL'}  ${fx.config.name.padEnd(30)} ` +
    `py £${(totalPy / 100).toFixed(2).padStart(9)}  js £${(totalJs / 100).toFixed(2).padStart(9)}  ` +
    `worst day diff ${worstDiff.toExponential(2)}${worstDay && worstDiff > 1e-6 ? ` (${worstDay}, ${badDays} days differ)` : ''}`
  );
}
console.log(failed ? `\n${failed} config(s) FAILED` : '\nall configs match Python exactly');
process.exit(failed ? 1 : 0);
